# Book settings
title: 데이터 사이언스 스쿨
author: ""
logo: logo.svg

repository:
  url: https://github.com/datascienceschool/book
  path_to_book: "ds"
  branch: master

parse:
  myst_extended_syntax: true
  
html:
  google_analytics_id: "UA-77195005-1"
  comments:
    hypothesis: true
    utterances:
      repo: "datascienceschool/book"

execute:
  execute_notebooks: 'off'
  
latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    show_authors: false
    html_show_copyright: false